# docker-compose.yml
services:
  backend:
    build:
      context: ./backend
    container_name: my-fastapi-app
    ports:
      - "8001:8001"
    env_file:
      - ./backend/localhost.env
    volumes:
      - ./backend:/app
    # depends_on:
    #   # Указываем, что бэкенд зависит от Triton.
    #   # Docker Compose запустит Triton и дождется его старта
    #   - triton

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "3000:80" # Левая цифра - порт на вашем компьютере, правая - порт внутри контейнера (у Nginx это 80)
    restart: unless-stopped
  triton:
    build:
      context: ./triton
    container_name: triton_server
    shm_size: '16g'
    ulimits:
      memlock: -1
      stack: 67108864
    # ports:
    #   - "25565:8000" # HTTP port
    #   - "8001:8001" # gRPC port
    #   - "8002:8002" # Metrics port
    # environment:
    #   - LD_LIBRARY_PATH=/usr/local/nvidia/lib:/usr/local/nvidia/lib64
    volumes:
      - ./triton/model_repository:/models
    command: tritonserver --model-repository=/models

    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]
  proxy:
   build: ./proxy
   ports:
     - "25565:5000"