name: Frontend CI Checks

# Триггеры:
on:
  pull_request:
    branches:
      - main
    paths:
      - 'frontend/**' # Запускать, только если в frontend

  push:
    branches:
      - '*'
    paths:
      - 'frontend/**' # Запускать, только если в frontend

jobs:
  lint-build-test:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: ./frontend

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Node.js v18
        uses: actions/setup-node@v4
        with:
          node-version: 18
          cache: 'npm'
          cache-dependency-path: frontend/package-lock.json

      # Зависимост ('npm ci' для эффективности)
      - name: Install dependencies
        run: npm ci

      # Запуск линтера и проверка форматирования
      - name: Run linter and code formatter check
        run: npm run lint

      - name: Build production version
        run: npm run build
